import request from '@/utils/request'
const root = '/governance/kettle'
const id = value => encodeURIComponent(String(value))
export const kettleStatus = () => request({ url: `${root}/status` })
export const kettleCatalog = () => request({ url: `${root}/catalog`, timeout: 90000 })
export const kettleDefinitions = () => request({ url: `${root}/definitions` })
export const kettleDefinition = value => request({ url: `${root}/definitions/${id(value)}` })
export const createKettleDefinition = data => request({ url: `${root}/definitions`, method: 'post', data })
export const saveKettleDefinition = (value, data) => request({ url: `${root}/definitions/${id(value)}`, method: 'put', data })
export const importKettleDefinitions = data => request({ url: `${root}/imports`, method: 'post', data, timeout: 90000, headers: { 'Content-Type': 'multipart/form-data', repeatSubmit: false } })
export const validateKettleDefinition = value => request({ url: `${root}/definitions/${id(value)}/validate`, method: 'post', timeout: 90000 })
export const kettleInputFiles = value => request({ url: `${root}/definitions/${id(value)}/files` })
export const uploadKettleInputFile = (value, data) => request({ url: `${root}/definitions/${id(value)}/files`, method: 'post', data, timeout: 60000, headers: { 'Content-Type': 'multipart/form-data', repeatSubmit: false } })
export const deleteKettleInputFile = (definition, file) => request({ url: `${root}/definitions/${id(definition)}/files/${id(file)}`, method: 'delete' })
export const runKettleDefinition = (value, data) => request({ url: `${root}/definitions/${id(value)}/runs`, method: 'post', data, timeout: 90000, headers: { repeatSubmit: false } })
export const kettleRun = value => request({ url: `${root}/runs/${id(value)}` })
export const kettleRunHistory = value => request({ url: `${root}/definitions/${id(value)}/runs` })
export const kettleEvents = (value, after = 0) => request({ url: `${root}/runs/${id(value)}/events`, params: { after } })
export const stopKettleRun = value => request({ url: `${root}/runs/${id(value)}/stop`, method: 'post' })
export const downloadKettleOutput = (value, filename) => request({ url: `${root}/runs/${id(value)}/files/${id(filename)}`, responseType: 'blob', timeout: 60000 })

export const kettleSchedules = value => request({ url: `${root}/definitions/${id(value)}/schedules` })
export const createKettleSchedule = (value, data) => request({ url: `${root}/definitions/${id(value)}/schedules`, method: 'post', data })
export const updateKettleSchedule = (value, data) => request({ url: `${root}/schedules/${id(value)}`, method: 'put', data })
export const setKettleScheduleState = (value, data) => request({ url: `${root}/schedules/${id(value)}/state`, method: 'post', data })
export const runKettleSchedule = value => request({ url: `${root}/schedules/${id(value)}/run`, method: 'post', headers: { repeatSubmit: false } })
export const recoverKettleSchedule = value => request({ url: `${root}/schedules/${id(value)}/recover`, method: 'post' })
