// Keys are the native Kettle XML paths, verified against the supplied task exports/default metadata.
export const valueTypes = ['String', 'Integer', 'Number', 'BigNumber', 'Date', 'Boolean', 'Binary', 'Serializable', 'Internet Address']
const f = (key, label, type = 'text', options) => ({ key, label, type, options })
const yes = (key, label) => f(key, label, 'boolean')
const field = (key, label) => f(key, label, 'field')
const table = (path, label, columns, defaults = {}) => ({ path, label, columns, defaults })
const types = f('type', '类型', 'select', valueTypes)
const basicField = [f('name', '字段名'), types, f('length', '长度'), f('precision', '精度'), f('format', '格式')]
const textField = [...basicField, f('currency', '货币符号'), f('decimal', '小数点'), f('group', '分组符'), f('trim_type', '去除空白', 'select', ['none', 'left', 'right', 'both'])]
const connection = f('connection', '数据库连接', 'connection')
const scriptTable = table('jsScripts/jsScript', 'JavaScript脚本', [f('jsScript_name', '脚本名称'), f('jsScript_type', '执行阶段', 'select', [{ value: '0', label: '逐行转换' }, { value: '1', label: '开始脚本' }, { value: '2', label: '结束脚本' }]), f('jsScript_script', '脚本', 'code')], { jsScript_name: '转换脚本', jsScript_type: '0', jsScript_script: '' })
export const nodeSchemas = {
  CsvInput: { group: '输入', fields: [f('filename', '输入文件', 'inputFile'), f('separator', '分隔符'), f('enclosure', '文本包围符'), yes('header', '首行为字段名'), f('encoding', '编码'), f('buffer_size', '缓冲区大小'), yes('lazy_conversion', '延迟类型转换'), yes('newline_possible', '字段内允许换行'), field('rownum_field', '行号字段'), yes('include_filename', '输出文件名')], tables: [table('fields/field', '输入字段', textField, { type: 'String', length: '-1', precision: '-1', trim_type: 'none' })] },
  TextFileInput: { group: '输入', fields: [f('file/name', '输入文件', 'inputFile'), f('file/filemask', '文件匹配规则'), f('file/type', '文件格式', 'select', ['CSV', 'Fixed']), f('separator', '分隔符'), f('enclosure', '文本包围符'), f('encoding', '编码'), yes('header', '包含表头'), f('nr_headerlines', '表头行数'), yes('noempty', '忽略空行'), f('limit', '读取行数（0为全部）')], tables: [table('fields/field', '输入字段', [...textField, f('position', '起始位置')], { type: 'String', length: '-1', precision: '-1' })] },
  TableInput: { group: '输入', fields: [connection, f('sql', 'SQL查询', 'code'), f('limit', '读取行数（0为全部）'), f('lookup', '提供查询参数的步骤', 'node'), yes('execute_each_row', '每个输入行执行一次'), yes('variables_active', '替换SQL中的变量'), yes('lazy_conversion_active', '延迟类型转换')] },
  KafkaConsumer: { group: '输入', fields: [f('TOPIC', 'Topic'), f('FIELD', '消息字段'), f('KEY_FIELD', '消息Key字段'), f('LIMIT', '读取条数限制'), f('TIMEOUT', '等待超时（毫秒）'), f('STOPONEMPTYTOPIC', 'Topic为空时停止', 'presence'), f('KAFKA/zookeeper.connect', 'ZooKeeper连接'), f('KAFKA/group.id', '消费组'), f('KAFKA/auto.offset.reset', '起始位置', 'select', ['smallest', 'largest']), f('KAFKA/auto.commit.enable', '自动提交位点', 'select', ['true', 'false']), f('KAFKA/zookeeper.connection.timeout.ms', 'ZooKeeper连接超时')] },
  KafkaProducer: { group: '输出', fields: [f('TOPIC', 'Topic'), field('FIELD', '消息字段'), f('KAFKA/metadata.broker.list', 'Broker列表'), f('KAFKA/producer.type', '发送方式', 'select', ['sync', 'async']), f('KAFKA/request.required.acks', '确认级别', 'select', ['-1', '0', '1']), f('KAFKA/serializer.class', '序列化类')] },
  JsonInput: { group: '输入', fields: [yes('IsInFields', '从前序字段读取'), field('valueField', 'JSON来源字段'), yes('IsAFile', '来源字段为文件名'), yes('readurl', '来源字段为URL'), f('file/name', 'JSON文件', 'inputFile'), yes('removeSourceField', '移除来源字段'), yes('ignoreMissingPath', '忽略缺失路径'), yes('defaultPathLeafToNull', '缺失叶子返回空值'), yes('IsIgnoreEmptyFile', '忽略空文件'), yes('doNotFailIfNoFile', '无文件时不报错'), f('limit', '读取行数限制')], tables: [table('fields/field', 'JSONPath字段', [f('name', '输出字段'), f('path', 'JSONPath'), ...textField.slice(1), yes('repeat', '重复取值')], { type: 'String', length: '-1', precision: '-1', trim_type: 'none', repeat: 'N' })] },
  ScriptValueMod: { group: '处理', fields: [yes('compatible', '兼容模式'), f('optimizationLevel', '脚本优化级别')], tables: [scriptTable, table('fields/field', '脚本输出字段', [...basicField.filter(item => item.key !== 'format'), f('rename', '重命名'), yes('replace', '替换原字段')], { type: 'String', length: '-1', precision: '-1', replace: 'N' })] },
  DBLookup: { group: '处理', fields: [connection, f('lookup/schema', 'Schema'), f('lookup/table', '查询表'), yes('cache', '启用缓存'), f('cache_size', '缓存行数'), yes('cache_load_all', '预加载全部查询数据'), f('lookup/orderby', '排序字段'), yes('lookup/fail_on_multiple', '多行命中时报错'), yes('lookup/eat_row_on_failure', '未命中时丢弃该行')], tables: [table('lookup/key', '查找条件', [field('name', '输入字段'), f('condition', '比较', 'select', ['=', '<>', '<', '<=', '>', '>=', 'LIKE', 'BETWEEN', 'IS NULL', 'IS NOT NULL']), f('field', '数据库字段'), field('name2', '第二输入字段')], { condition: '=' }), table('lookup/value', '返回字段', [f('name', '数据库字段'), f('rename', '输出字段名'), f('default', '未命中默认值'), types], { type: 'String' })] },
  SelectValues: { group: '处理', fields: [yes('fields/select_unspecified', '保留未指定字段')], tables: [table('fields/field', '选择与重命名', [field('name', '输入字段'), f('rename', '输出字段'), f('length', '长度'), f('precision', '精度')]), table('fields/remove', '删除字段', [field('name', '字段')]), table('fields/meta', '类型转换', [field('name', '输入字段'), f('rename', '输出字段'), types, f('length', '长度'), f('precision', '精度'), f('conversion_mask', '转换格式'), f('date_format_timezone', '时区'), f('date_format_locale', '语言区域'), f('encoding', '编码'), f('decimal_symbol', '小数点'), f('grouping_symbol', '分组符'), f('date_format_lenient', '宽松日期解析', 'truefalse'), f('lenient_string_to_number', '宽松数字解析', 'truefalse')], { type: 'String', length: '-1', precision: '-1' })] },
  SwitchCase: { group: '处理', fields: [field('fieldname', '分支字段'), yes('use_contains', '使用包含匹配'), f('case_value_type', '比较值类型', 'select', valueTypes), f('case_value_format', '比较值格式'), f('default_target_step', '默认目标步骤', 'node')], tables: [table('cases/case', '分支条件', [f('value', '匹配值'), f('target_step', '目标步骤', 'node')])] },
  FilterRows: { group: '处理', condition: true, fields: [f('send_true_to', '条件为真时发送到', 'node'), f('send_false_to', '条件为假时发送到', 'node')] },
  Constant: { group: '处理', fields: [], tables: [table('fields/field', '新增常量', [...basicField, f('nullif', '常量值'), yes('set_empty_string', '使用空字符串')], { type: 'String', length: '-1', precision: '-1', set_empty_string: 'N' })] },
  RowGenerator: { group: '输入', fields: [f('limit', '生成行数'), yes('never_ending', '持续生成'), f('interval_in_ms', '生成间隔（毫秒）')], tables: [table('fields/field', '生成字段', [...basicField, f('nullif', '字段值')], { type: 'String', length: '-1', precision: '-1' })] },
  TextFileOutput: { group: '输出', fields: [f('file/name', '输出文件名'), f('file/extention', '扩展名'), yes('file/append', '追加写入'), yes('create_parent_folder', '创建父目录'), f('encoding', '编码'), f('separator', '分隔符'), f('enclosure', '文本包围符'), yes('enclosure_forced', '强制文本包围'), f('format', '换行格式', 'select', ['UNIX', 'DOS']), yes('header', '输出表头'), yes('footer', '输出表尾'), yes('file/split', '文件名包含步骤副本号'), yes('file/haspartno', '文件名包含分区号'), f('file/splitevery', '每个文件的行数'), yes('file/add_date', '文件名增加日期'), yes('file/add_time', '文件名增加时间'), yes('file/SpecifyFormat', '自定义时间格式'), f('file/date_time_format', '文件名时间格式'), yes('file/rename_file_name', '海康临时文件改名'), f('file/max_wait_time_ms', '海康滚动等待毫秒'), yes('fileNameInField', '从字段取得文件名'), field('fileNameField', '文件名字段')], tables: [table('fields/field', '输出字段顺序', textField, { type: 'String', length: '-1', precision: '-1', trim_type: 'none' })] },
  TableOutput: { group: '输出', fields: [connection, f('schema', 'Schema'), f('table', '目标表'), f('commit', '提交批次大小'), yes('use_batch', '批量插入'), yes('truncate', '写入前清空目标表'), yes('ignore_errors', '忽略插入错误'), yes('specify_fields', '指定字段映射'), yes('return_keys', '返回生成的主键'), field('return_field', '主键返回字段')], tables: [table('fields/field', '字段映射', [f('column_name', '数据库列'), field('stream_name', '输入字段')])] },
  InsertUpdate: { group: '输出', fields: [connection, f('lookup/schema', 'Schema'), f('lookup/table', '目标表'), f('commit', '提交批次大小'), yes('update_bypassed', '跳过更新')], tables: [table('lookup/key', '匹配条件', [field('name', '输入字段'), f('condition', '比较'), f('field', '数据库字段'), field('name2', '第二输入字段')], { condition: '=' }), table('lookup/value', '插入/更新字段', [f('name', '数据库列'), field('rename', '输入字段'), yes('update', '更新此字段')], { update: 'Y' })] },
  WriteToLog: { group: '处理', fields: [f('loglevel', '日志级别', 'select', [{value:'log_level_error',label:'错误'},{value:'log_level_minimal',label:'最少'},{value:'log_level_basic',label:'基本'},{value:'log_level_detailed',label:'详细'},{value:'log_level_debug',label:'调试'},{value:'log_level_rowlevel',label:'行级'},{value:'log_level_nothing',label:'不输出'}]), f('logmessage', '日志消息', 'textarea'), yes('displayHeader', '输出表头'), yes('limitRows', '限制日志行数'), f('limitRowsNumber', '最大日志行数')], tables: [table('fields/field', '日志字段', [field('name', '字段')])] },
  Dummy: { group: '处理', fields: [] },
  SPECIAL: { group: '作业', fields: [yes('start', '作为作业起点'), yes('dummy', '空操作节点'), yes('repeat', '重复执行'), f('schedulerType', '调度类型'), f('intervalSeconds', '间隔秒数'), f('intervalMinutes', '间隔分钟'), f('hour', '小时'), f('minutes', '分钟'), f('weekDay', '星期'), f('DayOfMonth', '每月日期')] },
  TRANS: { group: '作业', fields: [f('filename', '执行的转换', 'definition'), yes('wait_until_finished', '等待转换执行完毕'), yes('exec_per_row', '为每个结果行执行一次'), yes('clear_rows', '执行前清空结果行'), yes('clear_files', '执行前清空结果文件'), yes('parameters/pass_all_parameters', '传递所有参数'), yes('arg_from_previous', '从结果行取得参数'), yes('set_logfile', '单独记录日志'), f('logfile', '日志文件名'), f('loglevel', '日志级别', 'select', ['Error', 'Minimal', 'Basic', 'Detailed', 'Debug', 'Rowlevel'])], tables: [table('parameters/parameter', '参数传递', [f('name', '参数名'), f('stream_name', '来源字段'), f('value', '参数值')])] },
  FTP_PUT: { group: '作业', fields: [f('servername', 'FTP服务器'), f('serverport', '端口'), f('username', '账号'), f('password', '密码', 'password'), f('localDirectory', '本地目录'), f('wildcard', '文件名匹配规则'), f('remoteDirectory', '远程目录'), f('timeout', '超时'), yes('binary', '二进制传输'), yes('active', '主动模式'), yes('only_new', '只发送新文件'), yes('rename', '使用临时文件名'), f('renameSuffix', '临时文件后缀'), yes('remove', '成功后删除本地文件'), f('control_encoding', '控制连接编码'), f('proxy_host', '代理服务器'), f('proxy_port', '代理端口'), f('proxy_username', '代理账号'), f('proxy_password', '代理密码', 'password')] }
}
export function schemaFor(pluginId) { return nodeSchemas[pluginId] || { group: '其他', fields: [], tables: [] } }
export function presentationFor(node, catalog = []) {
  const matches = item => item.id === node.pluginId || item.aliases?.includes(node.pluginId)
  const plugin = catalog.find(item => matches(item) && item.loadable) || catalog.find(matches)
  const group = schemaFor(node.pluginId).group
  const category = group === '输入' ? 'source' : group === '输出' ? 'output' : ['SwitchCase', 'FilterRows', 'SPECIAL', 'TRANS'].includes(node.pluginId) ? 'route' : 'transform'
  const icon = ({ KafkaConsumer: 'Connection', KafkaProducer: 'Connection', TableInput: 'Coin', TableOutput: 'Coin', DBLookup: 'Coin', ScriptValueMod: 'EditPen', CsvInput: 'Document', TextFileInput: 'Document', TextFileOutput: 'Document', FilterRows: 'Filter', SwitchCase: 'Share', SPECIAL: 'VideoPlay', FTP_PUT: 'Upload', TRANS: 'Connection' })[node.pluginId] || 'Operation'
  return { label: plugin?.label || plugin?.name || node.pluginId, category, icon }
}
export const connectionSchema = [f('name', '连接名称'), f('type', '数据库类型', 'select', ['POSTGRESQL', 'MYSQL', 'ORACLE', 'MSSQL', 'SQLITE']), f('server', '服务器'), f('port', '端口'), f('database', '数据库'), f('username', '账号'), f('password', '密码', 'password'), f('access', '访问方式', 'select', ['Native', 'JNDI', 'ODBC'])]
